services:

  rmq:
    image: ${RABBITMQ_IMAGE_TAG}
    container_name: rmq
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
      - rmqdata:/usr/share/rabbitmq/data
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  producer:
    build: producer
    depends_on:
        - rmq
    environment:
        AMQP_URL: 'amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rmq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./producer:/usr/src/app/producer

  consumer1:
    build: consumer
    depends_on:
        - rmq
    environment:
        AMQP_URL: 'amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rmq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./consumer:/usr/src/app/consumer
  consumer2:
    build: consumer
    depends_on:
        - rmq
    environment:
        AMQP_URL: 'amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rmq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./consumer:/usr/src/app/consumer
volumes:
    rmqdata:
      driver: local

